name: OpenURL
on: 
  push:
    paths:
      - openurl/*
  pull_request:
    paths:
      - openurl/*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Build
      env:
        GO111MODULE: on
      run: go build -mod=vendor ./cmd/devctl
    - name: Test
      env:
        GO111MODULE: on
      run: go test -mod=vendor -race ./...